name: Autonomous Pionex Trader

on:
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 minutes
  workflow_dispatch:      # Allow manual triggering

jobs:
  trade:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests ccxt pynacl # pynacl for GitHub secrets if used by agent itself

      - name: Run Trading Agent
        env:
          PIONEX_API_KEY: ${{ secrets.PIONEX_API_KEY }}
          PIONEX_API_SECRET: ${{ secrets.PIONEX_API_SECRET }}
          GH_PAT: ${{ secrets.GH_PAT }}
          INITIAL_BUDGET_USDT: "40.0"
          TRADE_AMOUNT_PER_COIN_USDT: "10.0"
          TAKE_PROFIT_PCT: "0.05"
          STOP_LOSS_PCT: "0.02"
        run: python agent.py
